export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const AUTH_START = 'AUTH_START';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
